### ISSUE TITLE
adding a more general ranking facility for students of large courses and in contests with many tasks

### ISSUE THREAD

**Issue by romeorizzi** [cms-dev/cms#1062]
RIght now cms offers two ranking facilitie, one for admins and one for contestants.
The one for contestants is designed for competitions, but less suitable for the didactic use of cms.
We should add to the admin panel (under the "General" section) the possibility to let students visualize the ranking, or better, just a customizable subset of the columns of the current admin ranking.
In the admin panel, the admin is allowed to introduce renditions by being exposed to a check-boxes list of the same fields currenty comprising the admin ranking table.
The admin checks the fields that he judges suitable and/or compatible with privacy issues:
We can also possibly think of allowing the admin to insert more than one rendition by assigning them different names. Also, the admin could specify for each of these renditions/views whether they are accessibel to teaching-assistants and to students.

WHY TO DO THIS:
With this extra service students will not only get a feeling of where they stand compared with the rest of the class, but will also keep track of the problems that they have already solved and what they could do next.

ONE VERY SMALL IMPROVEMENT:
One last point: the current order of the fields would be just better with a very small change: put the total score field just before all the other score fields, since this would make it much more easier for the instructor to immidiately associate a total score to a student in contests with many many tasks. And this small change might actually be an improvement also in case of few tasks.

**Comment by stefano-maggiolo** [comment]
Not sure I understand, in particular the part about "checking the suitable fields".

Is this what you want?
- offer one or more rankings visible in CWS (the contestant interface)
- each of this only shows a subset of the tasks, selected by the admin

**Comment by romeorizzi** [comment]
Not the first.
Yes, the second. More precisely: unrestricted administrators can define from the admin panel one or more possible views on the rankings csv file. Specifying a view means not only specifying a subset of the tasks but also of other fields (first_name, last_name, usernamename) currently displayed in ranking.csv. The subset can be conveniently specifyed by checking/uncheckin the checks asociated which each field.
The administrator also specifyies from the admin panel whether this view of the ranking file can be visualized (and downloaded) also by the students.

As a last suggestion: I think the currently last column (the field with the total score) would be better placed just before all the scores on the various tasks. (Thus I am not asking to allow the administrator to specify the order among the fields, so that everything remains simple).

**Comment by stefano-maggiolo** [comment]
I think this FR is a bit too specific to be of general use, so I'm going to close it

The good news is that I think it's not too hard to do what you want, and in a more flexible way, using what CMS already provides. The way we designed it, CMS doesn't force to have a specific ranking software; the default is RWS, but you can hook whatever you like, and the protocol is quite easy. 

The easiest thing you could do is to have slightly tweaked versions of RWS (say, one that ignores all tasks that are not in the list you want) and use those instead of plain RWS. This doesn't give you csvs, though.

More sophisticated, you can implement your own ranking. The idea is that you implement an HTTP server that listens to the data sent by ProxyService (https://github.com/cms-dev/cms/blob/master/cms/service/ProxyService.py#L302 and https://github.com/cms-dev/cms/blob/master/cms/service/ProxyService.py#L367, but you can also look at the JS console of RWS to see the protocol) and then you can expose whatever you like.
