### ISSUE TITLE
How install gcj-jdk on Ubuntu 18.10

### ISSUE THREAD

**Issue by vuhatuananh** [cms-dev/cms#1072]
I used command on Ubuntu 18.10 
sudo apt-get install nginx-full python2.7 php7.2-cli php7.2-fpm \
phppgadmin texlive-latex-base a2ps gcj-jdk haskell-platform rustc \
mono-mcs

But gcj-jdk can not install. Show me to fix it!

Thanks!

**Comment by lerks** [comment]
Apparently GCJ was abandoned in 2017 and hasn't been included in Ubuntu since 18.04. You can remove it from the command line (and we should probably update the doc, thanks for reporting it).

I don't think there is any reason to prefer GCJ over a JDK for Java programs, so you could install OpenJDK for example and be fine.

**Comment by vuhatuananh** [comment]
Contest configuration form has a option "Java 1.4 / gcj", so CMS can remove it.

![image](https://user-images.githubusercontent.com/44777595/48281484-53a86f00-e489-11e8-853e-dfe54f57e4e5.png)

**Comment by andreyv** [comment]
The `Java 1.4 / gcj` programming language is now removed. You can use `Java / JDK` instead.

Documentation is updated as well.
