### ISSUE TITLE
While installing cms on Ubuntu 20.04. Cannot Initialize database after configuring cms.conf.

### ISSUE THREAD

**Issue by inspiredgoose911** [cms-dev/cms#1204]
So I tried to install CMS following the official instruction but get stuck [here](https://cms.readthedocs.io/en/v1.2/Running%20CMS.html#configuring-the-db). I don't know if it is to proceed further without initializing db. I've already searched in internet to solve this issue but didn't find anything relevant to solve it. The only thing that I cannot understand is how to make connection to db in cms.conf file. I am new to this actually. Maybe I am not understanding simple stuff.
![Screenshot from 2022-04-22 10-45-51](https://user-images.githubusercontent.com/53224250/164604973-7508c339-e5e5-4323-a2a0-5ec4dce841f6.png)

**Comment by wil93** [comment]
This looks like a version mismatch, make sure that you're running the supported version of python and of the dependencies

**Comment by inspiredgoose911** [comment]
Is there any video instructions?

**Comment by inspiredgoose911** [comment]
> Is there any video instructions?

**Comment by inspiredgoose911** [comment]
> This looks like a version mismatch, make sure that you're running the supported version of python and of the dependencies

Is there any decent video instructions?

**Comment by wil93** [comment]
There was someone who made a video tutorial years ago, but I don't remember who, so it would be hard to find.

Also, video tutorial are hard to "update" so if things changed you might get stuck again. The official documentation is always the best way 😄 

Try doing all the steps from scratch, making sure that you're running a supported Ubuntu version and installing the correct packages 👍

**Comment by maxswjeon** [comment]
So, this issue is closed with any information rather than "That python version may be unsupported"?  
So what should we do? Installing CMS on ubuntu 22.04 does not work, period? Then please update the document so no more people spend their precious time.  

I want a clear explanation. Does python 3.6 work? 3.7 work? or 3.8, 3.9, and 3.10? What about 3.11 which was released recently? What version should we target? There is almost no information in this thread.

**Comment by wil93** [comment]
Just chiming in to say, it's not polite to say "update the document so no more people spend their precious time". Is my time / the volunteers' time not precious? We also need to spend time to keep the documentation up to date. 🙂

To answer your question: I haven't used CMS in a long while, so I don't know what version of Python should be targeted. However, you, @maxswjeon, are more than welcome to test which version works and contribute by editing the documentation with your findings 🙂

**Comment by melongist** [comment]
Dear Sangwan Jeon.

My time is so~ precious too.

But, take a look at my batch installation scripts~ :)

<https://github.com/melongist/CSL/tree/main/CMS>
[CSL.png]
CSL/CMS at main · melongist/CSL<https://github.com/melongist/CSL/tree/main/CMS>
github.com<https://github.com/melongist/CSL/tree/main/CMS>




2022. 11. 14. 22:20, Sangwan Jeon ***@***.***> 작성:

﻿

So, this issue is closed with any information rather than "That python version may be unsupported"?
So what should we do? Installing CMS on ubuntu 22.04 does not work, period? Then please update the document so no more people spend their precious time.

I want a clear explanation. Does python 3.6 work? 3.7 work? or 3.8, 3.9, and 3.10? What about 3.11 which was released recently? What version should we target? There is almost no information in this thread.

**Comment by maxswjeon** [comment]
Sorry for the toxic comment. I was very upset not able to set up this. I heard much compliments about this, so I was looking forward to use this. Thank you both @wil93 and @melongist and I want to say sorry again for the toxic comment.

**Comment by magula** [comment]
My experience is that CMS does indeed not currently work with Python 3.10. [As the documentation says](https://github.com/cms-dev/cms/blob/master/docs/Installation.rst), Python should be at least version 3.8, and that is the supported version. We've had no issues with Python 3.8 or 3.9 and have been using the latter for some time now, so either of those two will probably work.
