### ISSUE TITLE
IntegrityError when compiling the same code twice in parallel

### ISSUE THREAD

**Issue by gollux** [cms-dev/cms#1214]
At the IOI, it often happens that during the submission storm at the end of the contest, we are getting errors like this:

```
WARNING	Worker,46		
File af7ffdbbf9f6ec5d2f3cbbc3c58f980519d89cb8 (Executable insects for compile submission 19699) caused an IntegrityError, ignoring.
```

I think these are caused by the same source being submitted multiple times, so the same binary is produced, and multiple workers try adding it to the database with the same hash.

It would be nice to handle this more gracefully, either by ignoring the integrity error in this case, or (preferably) by using `INSERT ... ON CONFLICT DO NOTHING` instead.

**Comment by magula** [comment]
We have also regularly observed this, and I agree that it's caused by identical sourcecode being submitted multiple times.

The warning is logged here:
https://github.com/cms-dev/cms/blob/f2355d65f5cfdd9016db2d3c8a050413b2640357/cms/db/filecacher.py#L361-L367

Perhaps the simplest solution would be just fine: Replace `warning` by `info`, so the logging level is the same as for when the file has been stored on the database without a collision. This would apply to any attempt of storing a file on the database a second time, not just when the file is sourcecode that has been submitted multiple times.

Trying to store a file on the database that is already there doesn't seem very dangerous to me, which is why I'm not sure it requires a warning. While I suppose it could indirectly point towards an implementation bug, it seems that the kind of bug that would have this as a result would usually have more drastic and obvious signs anyway.

Another simple approach would be to keep the `warning` level, but make the message more verbose and include a hint that this is likely safe if the file in question is a submission's executable, so admins wouldn't worry too much.

Or one could try to only suppress the warning in this specific case, but this seems rather complicated and requires changes in a few places which might not be worth it: Likely by adding a `suppress_integrityerror_warning` flag to the functions in the relevant chain, and setting it to `True` only when it's a submission compilation result that is to be stored.

But maybe you have a plan for this issue already, @wil93? :)

**Comment by wil93** [comment]
I think your suggestion of turning the `warning` into a `info` message makes total sense, as well as adding some extra explanatory words in the logged message. Do you want to make these change @magula?
