### ISSUE TITLE
How can I run cmsContestWebServer in background?

### ISSUE THREAD

**Issue by minhduc0512** [cms-dev/cms#1219]
I install it on ubuntu server. I use putty access and install over ssh. How can I run cmsContestWebServer in the background? When I close putty, the session ends and cmsContestWebServer also stops. I can't use nohup because it requires the "ask_contest" variable to be passed. I can use nohup for other services

**Comment by magula** [comment]
You can pass the `CONTEST_ID` as an argument: `cmsContestWebServer -a [CONTEST_ID]`.
But I'd recommend to either
1. use `tmux` (or `screen`) or, better yet for a maintainable system,
2. incorporate the CMS services into [systemd](https://wiki.archlinux.org/title/systemd) services.

Just to give an idea of the latter: A systemd service unit file for the CMS resource service could look like the following, and you could then run it as `systemctl start cms-resource`.
```
[Unit]
Description=CMS Resource Service
Requires=cms-log.service postgresql.service
After=cms-log.service postgresql.service
[Service]
Type=simple
EnvironmentFile=/home/cms/resource-service.conf
ExecStart=/path/to/cmsResourceService -a $CONTEST_ID 0
User=cms
Slice=cms.slice
[Install]
WantedBy=multi-user.target
```
This assumes there's also a file `/home/cms/resource-service.conf` containing `CONTEST_ID=` followed by the contest ID you want to run.

PS: Please fill in the issue template next time, instead of including it like this...
