### ISSUE TITLE
sudo cmsAdminWebServer

### ISSUE THREAD

**Issue by Oyuunbaatar** [cms-dev/cms#1252]
sudo cmsAdminWebServer
![Screenshot_1](https://github.com/cms-dev/cms/assets/45691601/82c070a7-409e-493a-a632-615249644c30)

**Comment by wil93** [comment]
From the error message it looks like the port 8889 is already in use, either because of another running software using the same port or (most likely) another instance of AdminWebServer that you started earlier and that has not terminated.

Consider using the support channels for this kind of issue (e.g. the gitter chat)
