### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by hvenev** [cms-dev/cms#286]
Python 2.7 is bugfixes only, there is no python 2.8 and there will never be. See pep 404 for details.

Are there any libraries used by cms that have not yet been ported to python 3?

**Comment by lerks** [comment]
I'm reopening this, as gevent has been ported to Python 3 (that's not news [1], I just haven't checked in a while).

As far as I know there's no dependency left blocking CMS from working on Python 3. I intend to try to run it, check whether something breaks and fix it. The final goal will be to have the same codebase run on both versions. I do not plan for CMS to become Python 3-only for the time being.

[1] https://github.com/gevent/gevent/issues/38

**Comment by wil93** [comment]
@lerks Why support python2? I think it would be harder to port from 2 to 2+3 than porting from 2 to 3

**Comment by lerks** [comment]
To minimize disruption. If it will get really hard to support both we may reconsider this.

**Comment by wil93** [comment]
FWIW, Ubuntu 16.04 does not ship with python 2 anymore, it must be explicitly installed. Moreover, /usr/bin/python now points to python 3 instead of python 2.

I think it would be reasonable to port to python 3 and support Ubuntu >= 16.04, from (say) cms 1.4

An example of code that is ugly for 2+3 is this: https://github.com/cms-dev/cms/blob/master/cms/server/admin/handlers/contestranking.py#L76L81

**Comment by lerks** [comment]
That's false. Ubuntu server is getting Python 3, the desktop edition still comes with Python 2. [1]

As to the code you point to: yes, it is ugly, but as you can see we already have it, hence it shouldn't be a big deal to keep it. Nor port the rest of the code.

[1] https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#Python_3

**Comment by wil93** [comment]
> That's false. Ubuntu server is getting Python 3, the desktop edition still comes with Python 2

Oh, my bad. I assumed that the [official docker container](https://hub.docker.com/_/ubuntu/) I am currently working with (`ubuntu:16.04`) was the desktop version, but of course it's the server version.

> As to the code you point to: yes, it is ugly, but as you can see we already have it

Yes we already have it because in that specific case I kept both variants (just like [this other case](https://github.com/cms-dev/cms/blob/019c2179629ea4b0b84e63033a1fcd82fb2292bb/cms/service/ResourceService.py#L41L44)). There are probably other places in the codebase where adding variants is needed to support 2+3.

I don't have anything against supporting both 2 and 3, I was just wondering if it was worth the hassle :stuck_out_tongue:

**Comment by wil93** [comment]
Now that #624 is merged, what's the plan for solving this issue? Can I help?

**Comment by lerks** [comment]
I'd say that actually trying to pass CMS through 2to3, run it, see what
breaks and fix it will be the next steps in this direction.

We definitely aim to target py3 for 1.4 but I guess right now we'd prefer
to first focus on getting rid of a backlog of PRs and issues.

**Comment by lerks** [comment]
I've just pushed a few PRs that make our codebase compatible with Python 2 and 3 at the same time. Or, at least, they do that just enough for all tests to pass. There are surely still issues that need to be spotted and fixed. Yet, we now officially support Python 3 and we welcome all adventurous testers to try out the master branch using Python 3 and report all issues they find. But please be aware of the risks and don't do that in any setting and with any data you care about!
