### ISSUE TITLE
"Waited too long" in cms test 1/110

### ISSUE THREAD

**Issue by nir-lavee** [cms-dev/cms#385]
Hi,

This is probably a small issue that I'm misunderstanding, forgive me if it's known (I couldn't find it). When running `cmsRunTests`, after some initial tests that seem to pass, I get:
```
==> Clearing old coverage data.
==> Starting LogService.
==> Starting ResourceService.
==> Starting Checker.
==> Starting Worker.
==> Starting ScoringService.
==> Starting AdminWebServer.
==> Starting RankingWebServer.
==> Created contest 10.
==> Created user with id 174.
==> Starting EvaluationService.
==> Starting ContestWebServer.
==> Starting ProxyService.
==> Running test cases ...
==> Created task batchstdio as id 22
==> Asking ProxyService/0 to terminate...
==> Starting ProxyService.
==> Running test 1/110: correct-stdio (c)
Traceback (most recent call last):
  File "./cmstestsuite/RunFunctionalTests.py", line 467, in <module>
    sys.exit(main())
  File "./cmstestsuite/RunFunctionalTests.py", line 450, in main
    passed, test_results = run_testcases(contest_id, user_id, test_list)
  File "./cmstestsuite/RunFunctionalTests.py", line 317, in run_testcases
    test.run(contest_id, task_id, user_id, lang)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0-py2.7.egg/cmstestsuite/Test.py", line 149, in run
    result_info = get_evaluation_result(contest_id, submission_id)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0-py2.7.egg/cmstestsuite/__init__.py", line 558, in get_evaluation_result
    raise FrameworkException("Waited too long for result.")
cmstestsuite.FrameworkException: Waited too long for result.
```

I should point out that everything works fine when I create a contest myself to test it. What is a good way to debug this?

I am using CMS 1.1.0.

Thanks in advance,
Nir

**Comment by stefano-maggiolo** [comment]
Hello Nir,

this is probably some setup problem, usually the problem is in isolate: make sure that the path the tests are using is the same, and in particular that it is suidded. One good method is to remove all the isolate binaries apart from one in /usr/local/bin or similar.

More in general, to debug these problems I usually do one or both of these:
1. start LogService before the tests - if a service is already up, the tests will use that instance instead of creating a new one; at least you will see if the problem was in compilation or evaluation or somewhere else;
2. change `keep_sandbox` to true in the configuration and inspect the sandbox afterwards - in particular, `run.log` to see the exit status of isolate, and `commands` to try again executing them from the shell.

**Comment by nir-lavee** [comment]
Deleting the `isolate` executable from the local git clone fixed it.

Thanks!
