### ISSUE TITLE
Faces and team flags in ranking web server

### ISSUE THREAD

**Issue by ashikoff** [cms-dev/cms#439]
Hello - I'm trying to use the full potential of RankingWebServer, so I've created files with pictures for each contestant and also file with flag for each team. Now my ranking folder contains the following subfolders with resources:

/faces/ - all jpg pictures of the participants are inside, named with logins - ex: ALB1.jpg
/flags/ - all jpg pictures with teams' flags are located here - named with team names - ALB.jpg
/teams/ - a json file for each team with 1 attribute , ex: {"name": "Albania"}, named with team abbrev ALB.json
/users/ - for each user one json file with added team abbrev, for example:
{"l_name": "Keta", "f_name": "Muhamed", "team": "ALB"} for ALB1.json

The behaviour is strange - I start the contest and the RWS and then copy my info over to /var/local/lib/ranking folder and then restart RWS. I got all the teams associated (users got a flag in their team column), but when I click on a user it doesn't show me the picture from /faces/ folder, instead it shows a flag of the team again.

Help me please :)

**Comment by ashikoff** [comment]
P.S. Additional info - If I start RWS and do not copy users folder (the one with json's for each user) then the pictures are shown ok, but ofc users are not associated with teams.

**Comment by lerks** [comment]
That's weird. Let's try to find out what's happening.

Could you try to see if RWS is actually finding and loading the user pictures? Do it by accessing directly an URL like `http://<ranking>/<possible prefix>/faces/<user abbr>` (notice: no extension!). If that correctly loads the image, then the fault is client-side. Otherwise it's server-side: please check the files are placed and named correctly, that they have the right permissions, etc.

If it's a client-side fault, please open the browser, navigate to the RWS, open a user detail page and then check the source of the page. In particular, check for an `img` element with ID `UserDetail_face`. See if it's source attribute is properly set. To do it, for example, open a JavaScript console and type `document.getElementById('UserDetail_face').src`. If that still returns a valid URL (like the ones you tried above) then it may be a browser fault (i.e. it's loading images from cache). Try cleaning the cache or forcing a refresh and see if images appear. Otherwise please tell us which URL is set in the `src` attribute.

Anyway, please be aware that on the user detail page both the user's picture and its team's flag are shown. The former on the left side and the latter in the center.

**Comment by lerks** [comment]
No response in almost 2 years, closing.
