### ISSUE TITLE
How to Change Java Compiler

### ISSUE THREAD

**Issue by ken8203** [cms-dev/cms#491]
Hello,

The default java compiler is `gcj`, but I would like to use `openjdk` as compiler.
And I found it's written in the code [here](https://github.com/cms-dev/cms/blob/master/cms/grading/__init__.py#L260).
Could I make configuration to change it, or just modify the code and reinstall it?

Thanks a lot!

**Comment by stefano-maggiolo** [comment]
Hi Ken, sadly it's not so easy - but if you're willing to use the master version (instead of the stable one) it should be doable.

The patches used at the IOI to use a real JDK can be found at https://github.com/artikz/cms/commits/oracle-jdk-support-new (last 4 patches). You can try patching these in and it should work - note that to correctly evaluate Java programs with openjdk (or any other JDK) CMS  need to disable the thread restrictions, so any solution (even in other languages) can launch other threads. This shouldn't be a problem as the runtime is computed as the sum of all thread times. 

We had  success from another person using those 4 commits, so it should work. Otherwise feel free to ping us on contestms@freelist.org or at https://gitter.im/cms-dev/cms

**Comment by ken8203** [comment]
Okay,
I'll try it.

Thanks. :)

**Comment by lerks** [comment]
This has been done c598dbd3c40c617e48507891133569939272ee03 and is now available in v1.3.
