### ISSUE TITLE
Make sure that CMS works when installed in a virtualenv

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#559]
See https://github.com/cms-dev/cms/pull/479 for history.

**Comment by myungwoo** [comment]
If I start ResourceService in /home/ubuntu
the error occurs,
```
2016-02-26 07:59:20,775 - INFO [Resource,0] Restarting (AdminWebServer, 0)...
2016-02-26 07:59:20,779 - ERROR [Resource,0] Unexpected error.
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/cms/io/service.py", line 77, in repeater
    func()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/cms/service/ResourceService.py", line 175, in _restart_services
    stderr=subprocess.STDOUT
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/subprocess.py", line 756, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

However, when I start RS in /home/ubuntu/cms
it works well.

I have no idea why...

**Comment by wil93** [comment]
@myungwoo if you used virtualenv then CMS thinks it's *not* installed, so ResourceService will look for `./scripts/<command>` instead of just running `<command>`.

**Comment by stefano-maggiolo** [comment]
Following discussion in the mailing list, if you run cms as installed in a virtualenv, where would you expect it to place the cache, log, ... directories?

**Comment by wil93** [comment]
Isn't it enough to specify a different directory in cms.conf like this?

    "log_dir": "...",
    "cache_dir": "...",

I think it should work because of [this](https://github.com/cms-dev/cms/blob/master/cms/conf.py#L231).

Anyway, another solution is to send logs to the main system logs (e.g. [to journald](http://stackoverflow.com/questions/34588421/how-to-log-to-journald-systemd-via-python) if we decide to depend on systemd) and to store the cache in /tmp

Or, we could support command line flags to specify options like these.

**Comment by andreyv** [comment]
If CMS is run from a systemd unit, then nothing needs to be done, systemd will simply collect stdout and stderr and forward to journal. Otherwise a program can use standard Unix syslog facilities (https://docs.python.org/3/library/syslog.html), and messages should be forwarded to systemd-journald too.

**Comment by lerks** [comment]
I think commits like 37f859cd35eb2cafe1726216c296eef09ab5e138 amd af988d7fa3f3452ede1e4fbd8365b2a62f299b6a addressed this issue. I personally ran multiple times CMS from a virtualenv, in non-installed mode, and it worked perfectly (for the record, I had used `setup.py develop` instead of `install`). As for the outstanding worries about which directories CMS would use, I think this can be solved by using the CMS_CONFIG environment variable to specify a custom configuration which can then specify custom directories. If you still feel virtualenvs aren't fully supported please describe the issues you're having and reopen this.
