### ISSUE TITLE
Add support for test users

### ISSUE THREAD

**Issue by akmohtashami** [cms-dev/cms#597]
Right now to test a contest before it begins(check if model solutions are accepted, etc. ) the contest's start time must be changed and then change back after the test is over. It would be both easier and more secure to specify some users as test. These users should be able to make submission in the contest no matter the stage of the contest.

**Comment by myungwoo** [comment]
I think negative delay time for user is the simplest method to handle this.
However, negative delay time for user is unable now.

Is there any better idea?

**Comment by akmohtashami** [comment]
What about adding a new field(a boolean like hidden for example)?

**Comment by akmohtashami** [comment]
Following my comment above, I think maybe allowing usage of starting_time field for specifying custom starting time for different users in normal contests would be a good idea(just like USACO-like contests however the ending time is determined just as it is being determined right now)

I think this might be a little cleaner than allowing negative delay values.

**Comment by myungwoo** [comment]
Firstly, there is no text input for starting_time in aws,
and already starting_time is used for other purpose,
so I think it is not a good idea even if starting_time is only used for USACO-like contest.

I think it seems adding boolean field is better rather than using starting_time field.

**Comment by wil93** [comment]
What about creating a corresponding User for each Admin? We will eventually need to create Admin users anyway, since the new AWS login page has become pretty much mandatory now.

I and @veluca93 (if I'm not mistaken) were talking about this some time ago, and we think that it's reasonable to associate a User to an Admin, so that he/she can login on CWS as well as AWS. When an Admin logs in CWS, all restriction are removed (interval between submissions, contest starting time, and so on). Also, I think it's reasonable to automatically add a (hidden) participation whenever an Admin logs in a contest where he/she is not participating yet.

**Comment by myungwoo** [comment]
I've just sent PR with single commit. It is just one of the suggestions.
How do you think about it?
@wil93 , @akmohtashami 

I just added field "is_super_user" in Participation table which the contestant isn't restricted by maximum number, minimum interval, and contest time.

**Comment by stefano-maggiolo** [comment]
Hi all, nice to see discussions progressing :)

I agree on Myungwoo's solution as it is simple and does the job. Me and other people in the dev group are still quite opposed to having a common type for admins and users, and definitely is a much larger change than what is required to support Amir's use case. I probably would have suggested to remove the restrictions for all hidden users, but maybe somebody uses them to mean "real users, just unofficial".
