### ISSUE TITLE
Pass output file to communication task's manager

### ISSUE THREAD

**Issue by akmohtashami** [cms-dev/cms#598]
Right now the manager for a communication task only has access to inputs of tests. Providing access to output file makes using this task type easier. (for interactive tasks or other tasks in which we need the output during interaction with the contestant's solution) 

Currently, it is possible to concatenate output and input file but this is much cleaner. Is there a chance that making this change cause problem for backward-compatibility? would it be better to use a new task type or to update this task type?

**Comment by stefano-maggiolo** [comment]
I think there is a misunderstanding here: manager programs in Communications are not like the graders in Batch, i.e., they are not executed after the contestant's program has run. See [this presentation](https://docs.google.com/presentation/d/1wBVv3ZM76wzBPIdhYa7GjONNu_DNvNNYShk7yTWGHdU) (in particular page 8) to see the schema of a communication task.

**Comment by akmohtashami** [comment]
That's true but they are responsible for providing the final score(number between 0 and 1) for the submission. So it also is a checker. (Actually right now for Communication task types, output files aren't used at all).

However I thought about this a little bit more. I think it'd be best to introduce a new task type instead of changing the old one by making the following changes:
The outcome will not be determined by the manager. The manager creates the output file like batch task-type which is then provided to checker(or compared using white-diff). Also I think that even after this change it's a good idea to provide the output file to the manager. There are some use cases where you might need the answer while interacting with the contestant.

**Comment by stefano-maggiolo** [comment]
Oh, I'm sorry I misunderstood (didn't have my coffee yet, it was actually pretty simple to figure out I had the wrong picture...)

Yes, the idea behind communication is that since the manager is isolated, it is easy to implement the checker within it and there is no reason to split it. I can see that you might see it cleaner not to have data and solution of the testcase bundle together in the input file, but probably it's because I have a more liberal way of what input and output mean (notice how I use data and solution instead of input and output there :).

Input and output are just the data needed for the task type; really we could have put a generic dictionary like for the managers: it is the task type that decided how to use them.

So for communication, the ship has sailed, what you were proposing initially is quite a breaking change. If you want to create your own CommunicationWithGrader feel free, but I don't see it as different enough from Communication to be worth inclusion.
