### ISSUE TITLE
CMS_CONFIG for RWS

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#617]
Allow people to specify the config for RWS via environment variables.

**Comment by wil93** [comment]
What about simply allowing to specify each setting with a command line flag? For RWS, these would be the flags: `--bind`, `--port`, `--login` (or `--username` and `--password`).

A `--config` flag could be optionally supported to load the other settings from some location.

**Comment by wil93** [comment]
What do you think of this commit algorithm-ninja/rws@1bd30958940d83332654783e4a0d42cf79a21b6f

**Comment by lerks** [comment]
I don't really see any advantage: it would make us split the config-related code over two files (making the code harder to read and maintain). From a user point of view it means having to deal with long command lines, and I can imagine that instead of typing them every time they would store them in a .sh file. But then why not have them write a config file and do it the proper way?

On the other hand I like the `--config` flag, even better than the environment variable. Yet, we could do both.

**Comment by wil93** [comment]
In the commit I linked both are supported (command line flags for single options *and* the `--config` flag for a configuration file).

**Comment by wil93** [comment]
OK, I tried to clean up that commit and now argparse is seamlessly integrated with the configuration object, so there is no duplication at all: algorithm-ninja/rws@1ec4c14b80bb3306e2294818d96ec85c5485ef97

I think this is the best way to handle a program's options because sometimes you don't want to use configuration files (e.g. when writing a Dockerfile it's much better to have a long line instead of having to keep and `COPY` configuration files around).

What do you think @lerks?

**Comment by lerks** [comment]
Sorry, I just don't like it.

**Comment by stefano-maggiolo** [comment]
I agree with @lerks, we have too many configurations at the moment to move all of them to command line arguments.

**Comment by lerks** [comment]
FYI, @wil93, in the PR I've written you can use `-` for the `--config` argument and then the config file will be read from stdin. It's ugly and it's not something I did on purpose (it comes automatically with using argparse), but it allows you to do everything from command line if you really want to.

**Comment by wil93** [comment]
@stefano-maggiolo Mmm but what is stopping us from moving them? I did that in the last commit I referred, so it can't be because there are too many options...

@lerks yeah it's kinda ugly, even more since the most sensible solution would be to use CLI arguments...

**Comment by stefano-maggiolo** [comment]
More code that can go out of sync, blanket of options when doing -h, more ambiguity in the order of evaluations, ...

**Comment by wil93** [comment]
It's basically the same amount of code, if there's something more it's because of type checking (which is good: right now I could crash RWS by putting invalid data in the configuration file) and help text (again something useful).

The -h screen is just beautiful IMHO, much more than reading those "comments" in the JSON file :P I would paste it here but I'm on my phone

What about the order of evaluation? What is it that's not clear?

**Comment by stefano-maggiolo** [comment]
It's not the same amount of code, it looks like because RWS has way fewer options than CMS - which we will make sense to change too if we start doing this for RWS. 

As for order of evaluation: if I do RWS --port=X and then it says "using configuration Y" it wouldn't be clear which one wins to me.

**Comment by wil93** [comment]
Most of CMS options are meant to be database fields IIRC, so the command line options will be much fewer. Moreover, some of those options likely make sense just for a subset of `cmsCommand`s, so they'll likely be distributed across different commands (and will be even much fewer)

**Comment by lerks** [comment]
As, apparently, you weren't satisfied with my previous explanation, I will expand. I understand that at times being able to override some parameters on the flight may be handy. I also understand that in the way you use CMS this might be more convenient that an actual file. Yet I think your case is not representative of how most people use CMS. More than that, passing command line parameters is not the way people should configure CMS, in their own best interest. Writing the parameters in a configuration file at first may be felt as an annoyance, but it allows for an easy, fast, reliable and safe launch afterwards. These are all qualities that, especially in the heat of a contest, under the stress of repairing some unexpected issues, are very valuable.

BTW, I think we're making a big fuss out of this.

**Comment by wil93** [comment]
But my proposal supports configuration files, so I still don't get why it's not a good proposal (aside from you not liking it :P)

**Comment by lerks** [comment]
Fixed in #618 .
