### ISSUE TITLE
You can easily get 100 in GroupThreshold

### ISSUE THREAD

**Issue by qnighy** [cms-dev/cms#721]
You can easily get 100 at a `GroupThreshold` task by submitting a code which always results in timeout, abort, kill, etc. These conditions are treated as `0.0`, which in turn is regarded as correct in `GroupThreshold`. This is the demonstration: [dump_2017-02-26.tar.gz](https://github.com/cms-dev/cms/files/802004/dump_2017-02-26.tar.gz)

In fact I've been suspicious about this for years but haven't tested because I was not using it. Is anyone using `GroupThreshold`?

**Comment by stefano-maggiolo** [comment]
Hi Masaki - you are completely right, but not everything is lost :)

The undocumented feature that make GroupThreshold safe is that you should use it with a comparator (e.g., with Batch task types) - the problem with Communication is that we tried to be "smart" and say "a comparator is actually not useful as it can be done in the manager", but this is a counter-example to that.

I see three solutions:
1. leave everything as it is (I just submitted 28b726c069c2b14615274cd0c4738437c89be447 to document that it should not be used with Communication)
2. change Communication to default to a different outcome in case where the outcome is "None"
3. change GroupThreshold to receive full score iff `0 < outcome <= T` instead of `0 <= outcome <= T` 

Given how many people responded to this issue, I think changing the interface of GT as in (3) is not a problem, much less than changing Communication anyway. What do you think?

**Comment by qnighy** [comment]
This problem is not of Communication. It is of task types other than OutputOnly -- please check out this
[dump_2017-03-08.tar.gz](https://github.com/cms-dev/cms/files/826923/dump_2017-03-08.tar.gz) . Here `just_find2` is Batch (with grader + checker), where `just_find` is Communication. If you need source codes, here it is: [threshold_example_20170308.tar.gz](https://github.com/cms-dev/cms/files/826926/threshold_example_20170308.tar.gz)

**Comment by qnighy** [comment]
If very big breaking changes were allowed, `1-T <= outcome <= 1` would be better, since it is monotone to the outcome. Otherwise I prefer the `0 < outcome <= T` solution.

**Comment by stefano-maggiolo** [comment]
And as always you are right :) I thought the checker was invoked even in case of some failure in the user submission but that is not the case: if the sandbox returns anything other than EXIT_OK, Batch sets outcome = 0.0.

What do you think of this? https://github.com/stefano-maggiolo/cms/commit/26dd6025f0e3c4ccf2cf5da507adff2f91f5241c

**Comment by qnighy** [comment]
I'm content with this. Thanks!
