### ISSUE TITLE
CMS Ranking HTML Issue

### ISSUE THREAD

**Issue by Ista2000** [cms-dev/cms#799]
When selecting the users, it does not color-code them. All the users are shown in the side-view in white.

**Comment by lerks** [comment]
Could you please provide additional information? For example: the version
of the code you're using, relevant information about your setup (are
proxies used? is data being live streamed or is it an ended contest? etc),
a screenshot, the browser and its version, the browser JavaScript logs, the
server logs (if they contain anything unusual), steps to reproduce (if you
did anything after loading the page), possibly a dump of the HTML DOM tree
at the time this happened (can be obtained through the chrome developer
tools for example), and so on.

**Comment by Ista2000** [comment]
I just downloaded it and started a test/dummy contest. I followed the exact steps as provided by the docs for installation. I downloaded the latest stable version. Yes, the data is from a live(test/dummy) contest.
Screenshot can be found here: 
As you can see, I have selected the two dummy users and their initials shows up in the side-view in white.
I installed and run CMS on Ubuntu in a virtual machine inside Windows.(I don't think this is a possible cause of the error).
The problem persists regardless of the browser. I tried in Chrome, Firefox and Edge.
The only change I made that was not in the installation page in the docs is the addition of the logo.

**Comment by lerks** [comment]
Thanks for the information! Could you please provide two more things:
- the logs of the browser JavaScript (in Chrome, open the developer tools (Shift+Ctrl+i), go to the "Console" tab and copy everything)
- the HTML DOM tree when the issue is appearing (again in the developer tools, go to the Element tab, right-click on the root `html` tag, select Copy > Copy element and put the results somewhere (e.g. gist, pastebin, etc.))

**Comment by Ista2000** [comment]
Javascript Logs: https://pastebin.com/zWz1gvTg
HTML DOM tree: https://pastebin.com/BMvKTwQr
Also I now noticed, this is the exact error that's popping up when I am clicking on the tick beside the user name.
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "H190L210,20L190,…".
Note: I added the team "Narmada" after creating this issue.

**Comment by lerks** [comment]
Thanks, this information is very useful! (especially the error you reported)
I haven't dug into it in depth yet, but I first want to rule out a possibility. I saw from the screenshot that you have a task called Sum that belongs to a contest called Test. Does the task have a non-zero maximum score? If you don't know how to find that out, post here the output of `cmsRWSHelper get task Sum`.

**Comment by Ista2000** [comment]
I don't know why but the `cmsRWSHelper get task Sum` gives Error 406 :/
Anyway, no, max score is 0. There are no test cases, no statements, nothing. But can this be a problem?

**Comment by Ista2000** [comment]
Also, one last thing. The polygon importer searches for 0x(Where x is the test number) as input and 0x.a as the expected output for the input. But the output files don't exist in polygon packages by default; instead, they include a solution code which the author has written in the package. Am I supposed to run each test manually on the solution code and generate the output?

**Comment by lerks** [comment]
Right, that 406 is something I already wanted to fix, thanks for reminding me.

The problem is that you have a zero maximum score: this causes the overview to divide by zero when calculating the position of the markers. This is an easy fix, though I don't expect many people will hit this bug for real contests. ;)

I don't know anything about the Polygon importer. Did you read through the documentation? http://cms.readthedocs.io/en/v1.3/External%20contest%20formats.html#polygon-format If that doesn't answer your question please open a separate issue.

**Comment by Ista2000** [comment]
Thank you, that helped. :)

**Comment by lerks** [comment]
Pushed as c98539b221a716bcb7232a1c521f2f4351b59ca3 and 947c7957c98c7caad5a2293e666c063988f67e86.
