### ISSUE TITLE
Column loid in fsobjects should be of type oid

### ISSUE THREAD

**Issue by veluca93** [cms-dev/cms#975]
**Description:** according to [postgres' documentation](https://www.postgresql.org/docs/9.1/static/vacuumlo.html), large objects ID should be stored in columns of type `lo` or `oid`, as otherwise utilities like `vacuumlo` do not recognize them as large object ids. 

**Steps to reproduce:**
1. Run `vacuumlo`

**Expected:** the files referenced by cms should not be deleted.

**Actual:** all the files stored by cms are deleted

**Comment by lerks** [comment]
It sems SQLAlchemy doesn't provide a type for `lo` but it does provide one of `oid`: http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#sqlalchemy.dialects.postgresql.OID

So I guess this issue is just a matter of using it for all relevant columns?

**Comment by veluca93** [comment]
Yes, that should be enough.

**Comment by lerks** [comment]
I did that in #977.

However, when writing it, I realized it doesn't really fix your problem: `vacuumlo` removes large objects that have no references, but since we only reference large objects in FSObjects, there may very well be an obsolete unreferenced FSObject that is keeping a reference to a large object and preventing it to be garbage collected. In short, to fix your issue we would need first a `vacuumfsobject`, which we don't have AFAIK.

**Comment by veluca93** [comment]
That's good :)
Well, not deleting files that could be deleted is better then deleting files that shouldn't, which makes this a significant improvement in my opinion.
Anyway, the `clean_file_tombstone.sql` contains a sort-of-`vacuumfsobject` step, so one could use that.

**Comment by stefano-maggiolo** [comment]
I think CleanFiles is the script that removes fsobjects and largeobjects that have no reference

**Comment by stefano-maggiolo** [comment]
Fixed in #977, now pushed.
